[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nps"
version = "0.1.0"
description = "A simple CLI for sampling point clouds from large volumetric datasets"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
license = "MIT"
authors = [{ name = "Jakob Troidl" }]
dependencies = [
    "click",
    "volara",
    "pocaduck",
]
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.scripts]
nps = "nps.main:main"

[tool.setuptools.packages.find]
include = ["nps"]
