data:
  path: "graphene://https://local.brain-wire-test.org/segmentation/1.0/test0_parents_v0"
  timestamp: 1746039407
  mip: 0

output: "/nrs/turaga/jakob/autoproof_data/new_pipeline_debug/points"

processing:
  num_workers: 280
  cpus_per_worker: 2
  queue: "local"
  fraction: 0.001
  block_size: 
    - 128
    - 128
    - 128